/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2020-05-01 11:23:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class health_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<link href=\"/tv/common/styleMain.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"/tv/common/health.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"/tv/common/notification.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"icon\" type=\"image/png\" href=\"/tv/pictures/icon.png\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/tv/script/includeHTML.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/tv/script/toggleMenu.js\"></script>\r\n");
      out.write("\t<script src=\"https://kit.fontawesome.com/a076d05399.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<title>TrackVision</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div w3-include-html=\"/tv/common/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".html\"></div>\r\n");
      out.write("        <a href=\"/tv/health\" class=\"button-refresh\">Refresh</a>\r\n");
      out.write("\r\n");
      out.write("         ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${health}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \r\n");
      out.write("    <div id=\"carre\"> <h1>Welcome, Oussama Bouachrine</h1></div>\r\n");
      out.write(" \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("          <div id=\"main1\">\r\n");
      out.write("      <div id=\"menu1\"  >\r\n");
      out.write("             \r\n");
      out.write("          <img  class=\"image\" src=\"/tv/pictures/doctor.png\" alt=\"\"/>\r\n");
      out.write("           \r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("     <div id=\"contenu1\" >\r\n");
      out.write("       <a  href=\"/tv/searchResidents\" class = \"icon1\" title=\"Search Residents \"> <img src=\"https://img.icons8.com/color/90/000000/search-property.png\" /> Search Residents</a> \r\n");
      out.write("       <a  href=\"/tv/data\" class = \"icon2\" title=\"Map \">   <img src=\"https://img.icons8.com/color/96/000000/place-marker.png\"/> Map </a>\r\n");
      out.write("       <a class = \"icon3\" title=\"Medical Statistics\">   <img src=\"https://img.icons8.com/color/96/000000/business-report.png\"/>   Statistics</a>\r\n");
      out.write("         \r\n");
      out.write("     </div>\r\n");
      out.write("   </div>  \r\n");
      out.write("   \r\n");
      out.write("    <div class=\"notify\">\r\n");
      out.write("          ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notif}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write(" <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write(" <script src=\"/tv/script/notification.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div id=\"footer\">\r\n");
      out.write("\t<div w3-include-html=\"/tv/common/footer.html\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tincludeHTML();\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\t\r\n");
      out.write("</body> \r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
